from typing import Protocol
from uuid import UUID

from account.application.models import User, UserRole


class IdentityProvider(Protocol):
    def user(self) -> User: ...
    def user_id(self) -> UUID: ...
    def user_roles(self) -> set[UserRole]: ...
    def is_authenticated(self) -> bool: ...
