from typing import Protocol

from account.application.models import JwtToken, TokenPayload


class JwtTokenProvider(Protocol):
    def validate(self, token: str) -> JwtToken: ...
    def create_access_token(self, payload: TokenPayload) -> JwtToken: ...
    def create_refresh_token(self, payload: TokenPayload) -> JwtToken: ...
